apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
#  namespace: ora
  labels:
    app: database
    version: 12.1.0.2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
      version: 12.1.0.2
  template:
    metadata:
      name: database
      labels:
        app: database
        version: 12.1.0.2
    spec:
      securityContext:
        fsGroup: 54321
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: data
          persistentVolumeClaim:
            claimName: oravol
#        - name: log
#          persistentVolumeClaim:
#            claimName: oralog
      # add your volume mount for your persistent storage here
      containers:
      - name: database
        command:
        - /home/oracle/setup/dockerInit.sh
        image: store/oracle/database-enterprise:12.2.0.1
        #image: container-registry.oracle.com/database/enterprise:12.2.0.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 6Gi
        ports:
          - containerPort: 1521
            hostPort: 1521
        volumeMounts:
           - name: dshm
             mountPath: "/dev/shm"
           - name: data
             mountPath: "/ORCL"
#           - name: log
#             mountPath: "/home/oracle/setup/log"
        env:
          - name: DB_SID
            value: ORCL
          - name: DB_PDB
            value: OraPdb
          - name: DB_PASSWD
            value: 1mflpw2r
          - name: DB_DOMAIN
            value: my.domain.com
          - name: DB_BUNDLE
            value: basic
          - name: DB_MEMORY
            value: 5g
      imagePullSecrets:
      - name: oracle
      #- name: oracle1
---
apiVersion: v1
kind: Service
metadata:
  name: database
  #namespace: ora
spec:
  selector:
    app: database
    version: 12.1.0.2
  ports:
  - protocol: TCP
    port: 1521
    targetPort: 1521
